### ISSUE TITLE
Fr Pluralization errors

### ISSUE THREAD

**Issue by Startouf** [tigrish/devise-i18n#109]
translation data {:one=>"une erreur a empêché ce (ou cette) %{resource} d’être enregistré(e) :",
    :other=>"%{count} erreurs ont empêché ce (ou cette) %{resource} d’être enregistré(e) :"} 
    can not be used with :count => 3

I've had several French Pluralization errors even with other components, I think it's a problem of using :other instead of :many, or something similar.

**Comment by Startouf** [comment]
Oooh wait, this one doesn't seem to come from devise-i18n but rather i18n itself... sorry

**Comment by Startouf** [comment]
Indeed, using `:many` instead of `:other` fixed the problem 

(sorry had closed the issue because I thought for a second it was part of the base i18n gem, but this actually is in the last lines of the devise_fr translation)

**Comment by JasonBarnabe** [comment]
It seems like something else is the problem here. I use one/other in my other stuff and I haven't seen any problems. [This](http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html) indicates it's just one/other too.

**Comment by JasonBarnabe** [comment]
This works for me, if anyone has additional info on the problem, feel free to start a new issue.
