### ISSUE TITLE
Devise locale file

### ISSUE THREAD

**Issue by h1k3n** [tigrish/devise-i18n#110]
I'm probably doing something wrong here, but i have set default locale (application.rb => config.i18n.default_locale = :el) and i have the gem, but i don't get the devise.el.yml file and thus i get error messages from the flash messages and such.

For the record, these are my gems that i use for bootstrap views, devise and rails i18n:
 gem 'devise-bootstrap-views'
 gem 'rails-i18n', '~> 4.0.0'
 gem 'devise-i18n'
 gem 'devise-i18n-views'

for the time being i copy-pasted the data but i would like to know.

**Comment by intuxicated** [comment]
What error message?

**Comment by h1k3n** [comment]
I have no idea what this was, it's been like a year since i posted it....
