### ISSUE TITLE
devise-i18n should only load available locales (if set)

### ISSUE THREAD

**Issue by deivid-rodriguez** [tigrish/devise-i18n#117]
I think it should do [the same thing rais-i18n does](https://github.com/svenfuchs/rails-i18n/blob/master/lib/rails_i18n/railtie.rb). Load only locales in `i18n.available_locales` if set, load every locale otherwise.

Is there's a reason to load everything?

**Comment by tigrish** [comment]
Good point.

**Comment by deivid-rodriguez** [comment]
Would you like a PR?

**Comment by tigrish** [comment]
:+1: Sure!
