### ISSUE TITLE
How to use inside Rails engine?

### ISSUE THREAD

**Issue by sebastiaandegeus** [tigrish/devise-i18n#124]
It is possible to use this gem inside another rails engine gem as a dependency? Simply adding it as a dependency inside the gemspec file does not work. But adding it to the main rails gemfile works. 

Thanks.

**Comment by johnnyshields** [comment]
This issue is not relevant to this lib and should be closed.

With Rails engines I recommend to put all dependencies in the root Gemfile. I18n is NOT scoped to engines, it is loaded globally.

**Comment by JasonBarnabe** [comment]
I don't know much about engines, so I don't have an opinion, but nothing here seems actionable.
