### ISSUE TITLE
Merge with devise-i18n-views

### ISSUE THREAD

**Issue by JasonBarnabe** [tigrish/devise-i18n#131]
I'm currently a maintainer of devise-i18n-views gem. I would like to propose that the functionality of that gem be merged into devise-i18n. I've read the comment in #13, but I'd like to present my case.

The purpose of any gem (or software in general) is to be useful to users. The purpose of both devise-i18n and devise-i18n-views is to provide i18n for devise. The fact that some of this i18n is done simply with locale files and some requires views included isn't of much consequence to the gem users. In fact, having them separate causes confusion for users and requires both projects to tell people to use the other.

The same confusion arises for contributors to the gems (https://github.com/mcasimir/devise-i18n-views/pull/68 https://github.com/tigrish/devise-i18n/issues/92). These contributors will also either only contribute to one project, or need to keep track of two separate projects. Having them as one will mean an easier job for contributors and likely more complete translations.

Finally, having one project will make it easier for me and you (the maintainer of this gem). Having additional people to look at pull requests or sync from localeapp will make us more responsive.

**Comment by tigrish** [comment]
I totally agree with you that a single I18n solution for devise would be best all round.

*However*, I have absolutely zero time at the moment to dedicate to this, is this something you would be willing to work on (more than happy to give you access to this repo)?

**Comment by JasonBarnabe** [comment]
Yes, I'd be happy to work on it myself.
