### ISSUE TITLE
Update locales from devise-i18n-views Localeapp

### ISSUE THREAD

**Issue by lukaselmer** [tigrish/devise-i18n#137]
Hi,

We added a new locale including translations at Localeapp, and we would like to release a new software version soon. Additionally, we use https://github.com/mcasimir/devise-i18n-views (which is migrated into this repo, according to the https://github.com/tigrish/devise-i18n/blob/master/CHANGELOG.md). Would it be possible to update the locales from Localeapp, and release a new version of devise-i18n? Can we help?

Cheers,
Lukas

**Comment by JasonBarnabe** [comment]
I've updated from Localeapp.

I'm waiting to release to give people time to provide the new missing translations from devise-i18n. Probably a few more weeks and then I will release. In the meantime you can always point your Gemfile to a specific commit on this repo.
