### ISSUE TITLE
views are not used by default

### ISSUE THREAD

**Issue by lksv** [tigrish/devise-i18n#140]
Thanks you for this awesome gem.
I'm using master branch (`gem 'devise-i18n', github: 'tigrish/devise-i18n', branch: 'master'`). Unfortunately rails still renders (old) devise views like:
```
Processing by Devise::SessionsController#new as HTML
  Rendered /home/lukas/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/app/views/devise/shared/_links.html.erb (27.6ms)
  Rendered /home/lukas/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/app/views/devise/sessions/new.html.erb within layouts/application (692.6ms)
Completed 200 OK in 981ms (Views: 944.8ms | ActiveRecord: 3.6ms)
```
When I generate views to my project by `rails g devise:views:i18n_templates` then everyting is OK.

The problem is that devise-i18n views are not included in the view paths. (At first I was suspicious that there is a wrong order in view paths array, I temporarily move default devise view away (`mv /home/lukas/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/app/views/devise/sessions/new.html.erb{,.bak}`) doesn't help).

**Comment by JasonBarnabe** [comment]
Fixed!
