### ISSUE TITLE
Devise doesn't produce localized link in confirmation email

### ISSUE THREAD

**Issue by modreoci** [tigrish/devise-i18n#144]
devise-i18n (1.0.1)

Devise doesn't produce localized link in confirmation email.

It has to be:

```
http://localhost:3000/sk/users/confirmation?confirmation_token=...
```

and is:

```
http://localhost:3000/users/confirmation?confirmation_token=...
```

routes.rb

``` ruby
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    root to: 'visitors#index'
    devise_for :users
    resources :users
    get "/pages/:id" => "high_voltage/pages#show", :as => :page, :format => false
  end
end
```

**Comment by Dreamersoul** [comment]
im having the same issue i tried to customize the email views and its not working the emails keep loading from
`gems/devise-i18n-1.6.5/app/views/devise/mailer/reset_password_instructions.html.erb`

**Comment by JasonBarnabe** [comment]
Is the email otherwise localized properly?
