### ISSUE TITLE
view not correct while you change custom devise view

### ISSUE THREAD

**Issue by qx** [tigrish/devise-i18n#154]
<%= f.submit t('.`sign_up`', :default => "Sign up"),  :class => "com-next-bgcolor reg-btn"%>
Not work.
I have to change like this manual?
   <%= f.submit t('`devise.registrations.new.sign_up`', :default => "Sign up"),  :class => "com-next-bgcolor reg-btn"%>

**Comment by JasonBarnabe** [comment]
What do you mean by "change"? If you're moving it to a new location, it won't work. Those "relative" keys are based on the view path. http://guides.rubyonrails.org/i18n.html#lazy-lookup

**Comment by qx** [comment]
@JasonBarnabe ,yes,I customized devise controll and view, so the i18n is not worked

**Comment by qx** [comment]
产品背景

**Comment by JasonBarnabe** [comment]
This is expected behaviour when you change the view path.
