### ISSUE TITLE
devise:views:pt-BR locale creating view with different name

### ISSUE THREAD

**Issue by ajmiciano** [tigrish/devise-i18n#156]
When I give this command `rails g devise:views:locale pt-BR` it generates a `devise.views.pt-BR.yml` file instead of `devise.pt-BR.yml`. So if I create a `devise.pt-BR.yml` file it does not recognize and continues with the standard gem translation. If I change this file or create one with the `devise.views.pt-BR.yml` name works.

**Comment by JasonBarnabe** [comment]
Fixed by #157.
