### ISSUE TITLE
Readme doesn't match with last release

### ISSUE THREAD

**Issue by anthony-robin** [tigrish/devise-i18n#160]
Generator command doesn't work with last published release (1.0.1).
I had to specifiy master branch on my gemfile to be able to use the generator command:

`gem 'devise-i18n', github: 'tigrish/devise-i18n', branch: 'master'`

**Comment by chaimann** [comment]
you can also use 
```
rails g devise:views:i18n_templates
```
instead
```
rails g devise:i18n:views
```

**Comment by JasonBarnabe** [comment]
The readme reflects the changes in #152 which haven't been released yet.
