### ISSUE TITLE
simple form generations fils

### ISSUE THREAD

**Issue by koenhandekyn** [tigrish/devise-i18n#161]
when having simple form in the gemfile the generators file with the below message.
without the simple form gem in the gemfile the generation of the templates is working fine.

```
Running via Spring preloader in process 34125
      invoke  Devise::I18n::SharedViewsGenerator
       exist    app/views/devise/shared
   identical    app/views/devise/shared/_links.html.erb
      invoke  Devise::I18n::MailerViewsGenerator
       exist    app/views/devise/mailer
   identical    app/views/devise/mailer/confirmation_instructions.html.erb
   identical    app/views/devise/mailer/password_change.html.erb
   identical    app/views/devise/mailer/reset_password_instructions.html.erb
   identical    app/views/devise/mailer/unlock_instructions.html.erb
      invoke  i18n:simple_form_for
Could not find "confirmations" in any of your source paths. Your current source paths are:
/Users/xxx/yyy/lib/templates/devise/simple_form_for
/Users/xxx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/devise-i18n-1.1.0/lib/generators/devise/templates/simple_form_for
```

**Comment by Gee-Bee** [comment]
Same issue here.
In `$GEM_HOME/gems/devise-i18n-1.1.0/lib/generators/devise` there is only `i18n` folder (no `templates` folder).
 In git repository there are folders under `devise-i18n/lib/generators/devise/templates/simple_form_for`.
Maybe a problem with packed gem?

**Comment by JasonBarnabe** [comment]
Those files were indeed missed in the list of files to include in the packaged gem. It should be fixed for the next release.

**Comment by glebm** [comment]
Any chance for a new release? This is blocking a thing I'm writing over at https://github.com/thredded

**Comment by glebm** [comment]
@JasonBarnabe Thank you! 🎉
