### ISSUE TITLE
Locale code for Vietnam doesn't follow ISO 3166-2

### ISSUE THREAD

**Issue by jung-hunsoo** [tigrish/devise-i18n#172]
I recently found that the locale code for Vietnam used in the gem 'devise-i18n' is 'vi', which conflicts with 'Virgin Islands, U.S.'. The ISO 3166-2 presents 'vi' code virgin islands US. ISO 3166-2 code for Vietnam is 'vn' respectively.

Why don't you support 'vn' or make an alias or make a copy file?

**Comment by JasonBarnabe** [comment]
While you are correct that "vi" is the ISO 3166-1 country code for the US Virgin Islands and not Vietnam, locales are not ISO 3166-1. They are ISO 639-1 alpha-2 language codes with an optional, capitalized ISO-3166-1 after. https://github.com/tigrish/iso#languages

In other words, "vi" is Vietnamese (the language) and VN is Vietnam (the country). This project defines "vi" only, but if you thought that the Vietnamese as spoken in Vietnam was different than "generic" Vietnamese, we would add "vi-VN".
