### ISSUE TITLE
Is ISO-639-2 possible?

### ISSUE THREAD

**Issue by Artoria2e5** [tigrish/devise-i18n#183]
The [current zh-HK file](https://github.com/tigrish/devise-i18n/blob/812819e/rails/locales/zh-HK.yml) is not written in Mandarin (`cmn`, often assumed for `zh` "Chinese"), but in Cantonese (`yue`), causing a mismatch in language tagging and user expectation when they select `zh-HK` -- Hong Kongese Chinese, or Mandarin written in Traditional characters with Hong Kong terminology. It would be great if someone can check whether 639-2 codes are supported and move `zh-HK` to something like `yue-HK` if there is some support.

**Comment by JasonBarnabe** [comment]
Users of this gem will likely also use https://github.com/svenfuchs/rails-i18n. That gem has zh-CN, zh-HK, zh-TW, and zh-YUE. It also includes ISO-639-2 locales, but does not include any Chinese locales for that standard.

So if the current zh-HK is actually zh-YUE, then I have no problem with renaming it. If possible, I would like to maintain backwards compatibility for people who are already using zh-HK. Can you provide a translation or give a suggestion on which other file I can copy to be mostly correct?

**Comment by Artoria2e5** [comment]
A good example for a correctly "zh-HK" (cmn) is given in tootsuite/mastodon/pull/1759, but that would require some relicensing from yookoala.

**Comment by JasonBarnabe** [comment]
Copying what happened in https://github.com/svenfuchs/rails-i18n/pull/423, I'm going to copy zh-HK to zh-YUE. As far as I can tell, the content currently at zh-HK.yml is a better fit as zh-YUE.yml. To maintain backwards compatibility, zh-HK.yml will remain as is, but translations should be free to update it per https://www.drupal.org/node/1975400#comment-7676947
