### ISSUE TITLE
Are we missing 'Sign out' or 'Log out' keys?

### ISSUE THREAD

**Issue by viktorsmari** [tigrish/devise-i18n#193]
I want to have a 'Log out' or 'Sign out' button, but I cannot find the translation key for it.

Does it not exist?

Should it not exist here under sessions:
https://github.com/tigrish/devise-i18n/blob/master/rails/locales/en.yml#L106

**Comment by JasonBarnabe** [comment]
I don't think devise provides a log out button in its views.

**Comment by viktorsmari** [comment]
But isn't it used in almost all apps? Should we not support it? Are we tied to the device views? Should I then take it up with them? I thought this was a big deal but I could not find a related discussion about it

**Comment by JasonBarnabe** [comment]
This gem exists to provide translations of the strings devise contains. There may be some source out there for translations of string used by almost all apps, but it's not this gem.
