### ISSUE TITLE
Security issue induced by German translation

### ISSUE THREAD

**Issue by lgavillet** [tigrish/devise-i18n#223]
A security issue has been induced by a German translation: https://www.localeapp.com/projects/377/translations/2034179?in_locale=1648

Source of the problem: 
```
devise.failure.invalid:  %{authentication_keys} oder Passwort ungültig.
devise.failure.not_found_in_database: %{authentication_keys}-Adresse oder Passwort ungültig. 
```

As those two translations are not exactly the same, it is possible to differentiate if, during login failure, an user exists in the database or not. This is actually a security treat, as if no locking mechanism has been setup, it is possible to check the existence of an user and then guess the password. 

Translation updated in: https://www.localeapp.com/projects/377/translations/2034179?in_locale=1648

**Comment by JasonBarnabe** [comment]
See https://github.com/plataformatec/devise/issues/4763.

**Comment by JasonBarnabe** [comment]
I don't think it should be looking up different keys so I filed the issue above, but the values should not be different anyway, based on what devise provides. It looks like I made a mistake in https://github.com/tigrish/devise-i18n/commit/768785a655c3374e34e93a10e12c02d1e5a7aad9#diff-eb19846118a4d36584de4bccd93b7a04 and this difference was propagated to some translations.

**Comment by JasonBarnabe** [comment]
I have updated all strings to be the same for these two keys.
