### ISSUE TITLE
Czech translation of Sign in

### ISSUE THREAD

**Issue by jonatanklosko** [tigrish/devise-i18n#225]
Hey, one of our translators taking care of the Czech translation noticed that a better translation of "Sign in" would be "Přihlásit se". I think of this line specifically (but this may apply to other places as well): https://github.com/tigrish/devise-i18n/blob/0beb0b6a60a87b21375b80300fed6ff565bf2fc0/rails/locales/cs.yml#L122

Some examples of popular websites using this wording below:

- Google

![image](https://user-images.githubusercontent.com/17034772/36285538-41d7b4d4-12ac-11e8-8b48-ab422f330452.png)

- Facebook

![image](https://user-images.githubusercontent.com/17034772/36285524-34a97838-12ac-11e8-823c-10d4f25901af.png)

- Airbnb

![image](https://user-images.githubusercontent.com/17034772/36285684-cd3c3c66-12ac-11e8-8304-61b0ce871258.png)

Does anyone being responsible for the Czech translation of Devise have an opinion on this? =)

**Comment by JasonBarnabe** [comment]
If you think it's better, please [update on localeapp](https://www.localeapp.com/projects/377) or create a pull request. There is no specific person responsible for each language that you need to check with.
