### ISSUE TITLE
English "Log in" / "Sign in"

### ISSUE THREAD

**Issue by jonatanklosko** [tigrish/devise-i18n#228]
@JasonBarnabe I noticed one really weird thing. [This commit](https://github.com/tigrish/devise-i18n/commit/e35d9598b6c9e41f5d3a5eab39d6415fbe381a37#diff-eb19846118a4d36584de4bccd93b7a04) changes "Sign in" to "Log in", even though "sign in", "signed in" is used all around (even the key is `sign_in`). I see no reason for using a different, inconsistent wording for that. Would you be open to me updating it in Localeapp?

**Comment by JasonBarnabe** [comment]
The update done here was to match what devise has. devise updated in https://github.com/plataformatec/devise/commit/67d8dd1e948b363523bb567417965b4c1cf4ed02. Not saying this was a good or bad change, but I want there to be no differences when using devise-i18n in English mode compared to vanilla devise.
