### ISSUE TITLE
Errno::EACCES: Permission denied on 1.6.3 version

### ISSUE THREAD

**Issue by wecanooo** [tigrish/devise-i18n#234]
Hi, there

I have an error when use devise-i18n 1.6.3 version.

![2018-07-09 12 49 26](https://user-images.githubusercontent.com/776959/42429890-cc2baa4c-8376-11e8-9aca-1e9b6cae4615.png)

I have two versions of devise-i18n gems (1.6.3, 1.6.2)
So, I tried to change gem version 1.6.2

```ruby
gem 'devise-i18n', '1.6.2'
```

After change and deploy my eb environment, I can fix problem.

**Comment by JasonBarnabe** [comment]
Sorry about that. I forgot to update the permissions on the files, and depending on how you run your server, you could get that error.

Can you try 1.6.4 that I just put out?
