### ISSUE TITLE
Empty invalid and not_found_in_database translations for zh-TW

### ISSUE THREAD

**Issue by iczman** [tigrish/devise-i18n#238]
With the current blank translations I can't show invalid messages for my users who fail to login.

`invalid` and `not_fonud_in_database` translations were removed with #114, but now Devise is settled on using `Invalid %{authentication_keys} or password.` for en, should we update all languages to this format?

zh-TW for example:
```
invalid: "%{authentication_keys}或密碼是無效的。"
not_found_in_database: "%{authentication_keys}或密碼是無效的。"
```

**Comment by JasonBarnabe** [comment]
This repo's English strings are a copy of devise's English strings. Strings in other languages should say the same thing as the English strings, unless there's a good, language-specific reason not to.

**Comment by iczman** [comment]
Could you clarify by "should say the same thing as the English strings"? Did you mean other languages should also display the English version of the strings?

**Comment by iczman** [comment]
If I use devise-i18n without adding my customized zh-TW yaml, when I failed to login the flash message will show `translation missing: zh-TW.devise.failure.sales_user.not_found_in_database`.

But if I add a `devise.views.zh-tw.yml` and fill in a string for key `not_found_in_database`, then the flash will properly display the string.

Does this mean should not have empty keys for translations?

**Comment by JasonBarnabe** [comment]
> Could you clarify by "should say the same thing as the English strings"?
The meaning of the message should be the same in all languages, unless there is a reason for them not to be.

> If I use devise-i18n without adding my customized zh-TW yaml, when I failed to login the flash message will show translation missing: zh-TW.devise.failure.sales_user.not_found_in_database.

Some languages are not complete in this project. If you want to contribute translations they would be very welcome. Short of doing that, your options are:
- Defining a custom file, like you did.
- Defining a fallback language, so that the messages show in e.g. English if they are not available in your chosen language.
- Live with the missing translations.

**Comment by JasonBarnabe** [comment]
Done in ed81f295b9f04fe5bb8dbf35089a200f8249a223. 謝謝!

**Comment by iczman** [comment]
Thanks!
