### ISSUE TITLE
Flash messages not localized

### ISSUE THREAD

**Issue by Vorkosigan76** [tigrish/devise-i18n#274]
Running Rails 6.0.1 + devise + devise_i18n

=> messages generated by devise and accessed via resource.errors.full_messages are localized
e.g. try to "sign_up" with no information filled in

=> flashes generated by devise are not localized
e.g. try to "sign_in" with no information filled in

**Comment by Vorkosigan76** [comment]
This seems to come from setting a failback locale.

**Comment by ToTenMilan** [comment]
You need to set
```
before_action :switch_locale

def switch_locale
  locale = params[:locale] || I18n.default_locale
  I18n.locale = locale
end
```
instead of [Rails guides way](https://guides.rubyonrails.org/i18n.html#managing-the-locale-across-requests):
```
around_action :switch_locale

def switch_locale(&action)
  locale = params[:locale] || I18n.default_locale
  I18n.with_locale(locale, &action)
end
```

Details in devise-i18n readme https://github.com/tigrish/devise-i18n#setting-your-locale
