### ISSUE TITLE
Wrong scoped views generation?

### ISSUE THREAD

**Issue by airled** [tigrish/devise-i18n#278]
Rails `6.0.2.2`, devise `4.7.1`, devise-i18n `1.9.1`.
I use scoped views for users and my default locale is `ru`;
```ruby
...
    config.i18n.available_locales = [:ru, :en, :es]
    config.i18n.default_locale = :ru
...
```

After I run `be rails g devise:i18n:views user` the gem genereates me all the views.
```bash
> be rails g devise:i18n:views user
invoke  Devise::I18n::SharedViewsGenerator
create    app/views/users/shared
create    app/views/users/shared/_error_messages.html.erb
create    app/views/users/shared/_links.html.erb
invoke  Devise::I18n::MailerViewsGenerator
create    app/views/users/mailer
create    app/views/users/mailer/confirmation_instructions.html.erb
create    app/views/users/mailer/email_changed.html.erb
create    app/views/users/mailer/password_change.html.erb
create    app/views/users/mailer/reset_password_instructions.html.erb
create    app/views/users/mailer/unlock_instructions.html.erb
invoke  i18n:form_for
create    app/views/users/confirmations
create    app/views/users/confirmations/new.html.erb
create    app/views/users/passwords
create    app/views/users/passwords/edit.html.erb
create    app/views/users/passwords/new.html.erb
create    app/views/users/registrations
create    app/views/users/registrations/edit.html.erb
create    app/views/users/registrations/new.html.erb
create    app/views/users/sessions
create    app/views/users/sessions/new.html.erb
create    app/views/users/unlocks
create    app/views/users/unlocks/new.html.erb
```

Fox example, login view looks like this
```erb
<h2><%= t('.sign_in') %></h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "current-password" %>
  </div>

  <% if devise_mapping.rememberable? %>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit t('.sign_in') %>
  </div>
<% end %>

<%= render "users/shared/links" %>
```

But when I hit `http://localhost:3000/users/sign_in` page looks like this:

![screen-2020-03-29-12-11-23](https://user-images.githubusercontent.com/10863999/77842633-6fafcc00-71b6-11ea-91cf-8e246299e990.jpg)

Also I noticed some incorrect path generation. Fox example, this is `confirmations/new` view:
```erb
<h2><%= t('.resend_confirmation_instructions') %></h2>

<%= form_for(resource, as: resource_name, url: confirmation_path(resource_name), html: { method: :post }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email) %>
  </div>

  <div class="actions">
    <%= f.submit t('.resend_confirmation_instructions') %>
  </div>
<% end %>

<%= render "users/shared/links" %>
```
It uses `render "users/shared/links"`, but errors renders from `render "devise/shared/error_messages"`.

If I replace all `t('.sign_in')` translations with absolute route as `t('devise.sessions.new.sign_in')` it works absolute fine. But what the point of automatic generation if I still have to replace translation keys by myself?

**Comment by JasonBarnabe** [comment]
Scoping of the keys seems to be referred to [here](https://github.com/tigrish/devise-i18n#scoped-views)

> You will additionally need to generate the translations into your app per the following section and then add keys in each file for the scope you are using.

But I don't see what it would need to be this way (except for maybe the activerecord branch of translations).

**Comment by airled** [comment]
> Scoping of the keys seems to be referred to [here](https://github.com/tigrish/devise-i18n#scoped-views)
> 
> > You will additionally need to generate the translations into your app per the following section and then add keys in each file for the scope you are using.
> 
> But I don't see what it would need to be this way (except for maybe the activerecord branch of translations).

Thanks for reply! Yes, I saw this section. My issue is, for example, why the gem can't generate `"devise.sessions.new.sign_in"` by default instead of `".sign_in"`. If I need it, I change it. The gem already uses default keys for form inputs (like `Пароль` (password) и `Запомнить меня` (remember me) fields on my screenshot.). Why can't use default translations for others?

**Comment by JasonBarnabe** [comment]
> The gem already uses default keys for form inputs (like Пароль (password) и Запомнить меня (remember me) fields on my screenshot.).

This is the "[activerecord branch of translations](https://github.com/tigrish/devise-i18n/blob/master/rails/locales/en.yml#L2-L31)" I mentioned. These are dependent on your model being called "User".

> why the gem can't generate "devise.sessions.new.sign_in" by default instead of ".sign_in"

That would be more sensible than making you edit the translation files as it suggests. Only downside could be if someone is depending on the current behaviour.

I would be open to a PR to fix this.

**Comment by airled** [comment]
@JasonBarnabe If it change compatibility it is better to create a new major version. My point is that the gem with `rails g devise:i18n:views user` should generate views with default devise I18n keys. If developer does not like default translation it can generate separate locale file. Becase 'Login'-value for example at most cases will be the same for all devise models. You can just use this default value and thats all.

The other workaround that does not break compatibility would be to introduce a new option like `--default` something like
`rails g devise:i18n:views users --default`. All users that depend on previous behaviour are not touched and someone who needs behaviour that I need can use this command. What do you think?

**Comment by JasonBarnabe** [comment]
I don't think we need to maintain the old behaviour behind an argument - just change it. But yes this would be 1.10.0 and not 1.9.2.

**Comment by airled** [comment]
OK. I close issue. Thanks
