### ISSUE TITLE
add "confirmed" to i18n

### ISSUE THREAD

**Issue by yshmarov** [tigrish/devise-i18n#284]
When using devise_confirmable we can run `user.confirmed?` to get `true `or `false`. 
**It would be great to have `confirmed` added to i18n.** 
Now we only have `confirmed_at` that logically returns a `datetime`

**Comment by yshmarov** [comment]
#285

**Comment by JasonBarnabe** [comment]
The other strings under `activerecord.attributes.user` are actually attributes of a User model that different configurations of devise could require. The translations could be used in validation messages, for example.

This doesn't seem to be the same kind of thing, so I would say it's not going to be added, unless given a good reason. If you need it, you can include it as a translatable string in your own project.

**Comment by yshmarov** [comment]
Makes sense.

My reasoning her is that `confirmed` method is standard for `Devise confirmable` and can be used quite often. 
For example, in a user view it is more natural to put `confirmed: true/false` than `confirmed_at: nil/DateTime`,
so it would be cool to have `confirmed` and possible some other methods available :)

**Comment by JasonBarnabe** [comment]
There are a lot of strings that could potentially be useful, but this project is limited to ones you would need to use devise.
