### ISSUE TITLE
Missing message when mail is unconfirmed in mailer email_changed

### ISSUE THREAD

**Issue by DiegoOrejuela** [tigrish/devise-i18n#286]
Hi Guys. Great gem!

I think that situation is sufficiently described in the title.
You can confirm in Devise that exist different messages when email is confirmed and unconfirmed, and locales (I review locale en.yml) only has message when email is confirmed.

Here link to [devise/app/views/devise/mailer/email_changed.html.erb](https://github.com/heartcombo/devise/blob/master/app/views/devise/mailer/email_changed.html.erb)

Thanks, stay tuned.

**Comment by JasonBarnabe** [comment]
[The same message is used in both cases, just like in Devise.](https://github.com/tigrish/devise-i18n/blob/master/app/views/devise/mailer/email_changed.html.erb)

**Comment by DiegoOrejuela** [comment]
> [The same message is used in both cases, just like in Devise.](https://github.com/tigrish/devise-i18n/blob/master/app/views/devise/mailer/email_changed.html.erb)

Can you review again, please?

You can look the code and messages are diferents:
when is unconfirmed:
`We're contacting you to notify you that your email is being changed to`
when is confirmed: 
`We're contacting you to notify you that your email has been changed to `

**Comment by JasonBarnabe** [comment]
Ah, didn't see that distinction. Yes, we should have different messages here, but don't currently.

**Comment by DiegoOrejuela** [comment]
Ah, ok. Thank you, and I will be checking for update!
