### ISSUE TITLE
Missing inactive account translation missing

### ISSUE THREAD

**Issue by zedtux** [tigrish/devise-i18n#294]
The Devise wiki page [How To: Customize user account status validation when logging in](https://github.com/heartcombo/devise/wiki/How-To%3A-Customize-user-account-status-validation-when-logging-in#customize-error-message) shows a way to customize the error message when the user is forbidden to login through the translation key `devise.failure.account_inactive` which is not available in this gem so it would be cool to add it.

**Comment by JasonBarnabe** [comment]
We're not going to add things that are not actually built in to devise. There are many ways devise's behaviour could be customized, and we can't support them all.
