### ISSUE TITLE
Possibly missing string

### ISSUE THREAD

**Issue by psychoslave** [tigrish/devise-i18n#301]
Hello,

I'm trying to solve https://github.com/openfoodfoundation/openfoodnetwork/issues/5782

As already explained in this message, I'm facing missing translation after the gem installation:
```
 Il y a eu un souci avec les champs suivants :
    Reset password token is invalid
```

I am not yet acculturated with the gem way to produce its yaml keys. From what I understand, `~/.rbenv/versions/2.5.9/lib/ruby/gems/2.5.0/gems/devise-4.8.0/lib/devise/models/recoverable.rb` is responsible for building keys while trying to change the password. But I see no sign of "invalid" symbol. There is one in `unauthenticated_message`, in `.rbenv/versions/2.5.9/lib/ruby/gems/2.5.0/gems/devise-4.8.0/lib/devise/models/authenticatable.rb `, but I didn't find any call to this method.

Any suggestion would be welcome. 🙏

**Comment by JasonBarnabe** [comment]
"is invalid" is coming from rails-i18n. https://github.com/svenfuchs/rails-i18n/blob/67d72ccf469c7e5aa50838b0090219bf579f2626/rails/locale/fr.yml#L126

The fact that neither "is invalid" nor "Reset password token" are being translated for you makes me think there's something wrong with how you set `I18n.locale`. Have you looked at https://github.com/tigrish/devise-i18n#setting-your-locale - specifically the warning against using `around_action`?

**Comment by psychoslave** [comment]
Hey @JasonBarnabe thanks for the hints. I'll dig into that when I can. I am not fully acquainted with how internationalization was set in the OFN repository yet. :smile:
