### ISSUE TITLE
Missing partial string `Reset password token`

### ISSUE THREAD

**Issue by psychoslave** [tigrish/devise-i18n#302]
Hello,

Similarly to #301 and still linked to https://github.com/openfoodfoundation/openfoodnetwork/issues/5782 I reached an other case of untranslated string. Or rather of partially untranslated string: 

>Reset password token est expiré, veuillez en demander un autre.

Which should be something like 

>  Le jeton de réinitialisation du mot-de-passe est expiré, veuillez en demander un autre.

**Comment by psychoslave** [comment]
Note that generating `config/locales/devise.views.fr.yml` allow to see there is a key `fr.activerecord.attributes.user.reset_password_token`:
> 23         reset_password_token: Clé de réinitialisation du mot de passe                                                                                                                                          

I tried to add the key with the same name in various position in the yaml tree, especially `[…].errors.messages.reset_password_token`, but even after rebooting Rails server, it still doesn't seem to work properly. 🤔

**Comment by JasonBarnabe** [comment]
I can't reproduce this, I get:

> Clé de réinitialisation du mot de passe est expiré, veuillez en demander un autre

So either it's been fixed or it was something specific on your end.
