### ISSUE TITLE
Undefined method 'user_url'

### ISSUE THREAD

**Issue by saint-james-fr** [tigrish/devise-i18n#329]
Same issue than discuted here 
https://github.com/heartcombo/devise/issues/5439

I had to add this in devise.rb after installing your gem
config.navigational_formats = ['*/*', :html, :turbo_stream]

Before everything was working. Do you have any idea why installing your gem caused this bug?
Anyway, thanks, love it, so useful!!

**Comment by JasonBarnabe** [comment]
If it's the same as https://github.com/heartcombo/devise/issues/5439 then it'll have to be fixed in devise. Once fixed there, it should be fixed here as well. We don't deviate from what devise does.
