### ISSUE TITLE
custom strings

### ISSUE THREAD

**Issue by prp-e** [tigrish/devise-i18n#344]
Greetings.

For devise views I have used `devise-i18n` gem and I added this section to the view:

    <div class="section orange-section">
      <h1><%= t('registration_tips')%></h1>
      <p><%= t('registrations_guide_html')%></p>
    </div>

and in the YML file, I did this:

    registrations:
     new:
      registration_tips: "some text"
      registration_guide_html: "some text"

But it doesn't work. How can I actually get it to work and display my texts correctly?

Thanks!

**Comment by JasonBarnabe** [comment]
Looks like you asked and received an answer [on Reddit](https://www.reddit.com/r/rails/comments/15vej28/devisei18n_custom_strings/).
