### ISSUE TITLE
using nokogiri 1.15 breaks devise emails

### ISSUE THREAD

**Issue by opensourceame** [tigrish/devise-i18n#345]
The 1.10.3 update of this gem also bumped Nokogiri to 1.15.  After this update Devise emails broke completely with the following error:

```
rails> User.first.send_confirmation_instructions

DeviseMailer#confirmation_instructions: processed outbound mail in 77.1ms
Nokogiri::XML::SyntaxError: Parser without recover option encountered error or warning: 1:1: FATAL: Growing input buffer
from /heroku/ruby/bundle/ruby/3.1.4/gems/nokogiri-1.15.4-x86_64-linux/lib/nokogiri/html4/document.rb:194:in `read_io'
```

Manually downgrading to 1.14 in `Gemfile.lock` solved the issue.

I would like to request that gem dependency updates be listed in the changelog as they can cause breaking changes.

**Comment by JasonBarnabe** [comment]
I'm using nokogiri 1.15.4 and devise-i18n 1.10.0, I don't see such a problem.

This sounds like a problem you have with nokogiri - I'm not sure what this gem could do that could cause such a thing.

**Comment by JasonBarnabe** [comment]
Also note this gem does not directly require nokogiri - it's a subdependency that gets included through some Rails stuff. If it's causing you problems, you're free to pin nokogiri to whatever version you like, but as stated above, I don't see the problem myself.
