### ISSUE TITLE
A proposed addition for the readme.md file

### ISSUE THREAD

**Issue by jules-w2** [tigrish/devise-i18n#348]
In my project I had added the devise-i18n gem before than the devise gem and the emails and views were therefore loaded from "devise"

```ruby
##============================================================##
## I18n
##============================================================##
gem "carrierwave-i18n"
gem "devise-i18n"
gem "i18n"
gem "i18n_data"
gem "rails-i18n"

.....


##============================================================##
## Users & Roles
##============================================================##
gem "devise"
gem "rolify"
```

I think it might be a good idea to add a note on this scenario in the readme.md file

----

the gem must be added in the gemfile after the devise gem to ensure that the views used come from the devise-i18n gem and not the default devise one

Bests

**Comment by JasonBarnabe** [comment]
Didn't even realize this was the case- readme has been updated.
