### ISSUE TITLE
Add Bulgarian (bg) language to locale project

### ISSUE THREAD

**Issue by AlexVPopov** [tigrish/devise-i18n#59]
Could you app Bulgarian (bg) to the locale app project, so that I can translate it. Thank you.

**Comment by buhtz** [comment]
Dear @AlexVPopov ,
my apologize for contacting you this way but I wasn't able to find a email address or something else.

I assume you are a native speaker of Bulgarian, right?

I'm looking for a translation of a [100 words text](https://translate.codeberg.org/translate/backintime/common/bg/?q=hello) into Bulgarian in the context of a backup software named [Back In Time](https://github.com/bit-team/backintime). The text is addressed to the users and tries to attract them contributing to the translation of the software they use them self.

Can you help us out here?
